### ISSUE TITLE
Test with Boost 1.62

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#158] opened 2016-09-16 15:23 UTC
Test if BUTA is compatible with the upcoming **Boost 1.62**:
- test with http://www.boost.org/users/history/version_1_62_0.html

**Boost.test v3.3** see the [Change log](http://www.boost.org/doc/libs/1_62_0_b2/libs/test/doc/html/boost_test/change_log.html) section for more details.
- **New features**
  - dataset driven test-cases have now a unique name and all sample tests of a dataset live inside the same test suite
  - Boost.test learned a new command line switch, --logger for setting a test logger as well as its parameter in one command
  - Boost.test learned to have several loggers at the same time, each of which having their own log level and output stream
  - Boost.test learned a new logger, JUNIT, that is able to output Junit/xUnit compatible streams
  - It is now possible to specify several test filters through the environment variable BOOST_TEST_RUN_FILTERS
- **Bug fixes**
  - Trac tickets #8707, #8834, #11128, #11845, #11859, #12024,
  - Trac tickets #12093, #12103, #12224, #12241, #12257, #12378
  - Pull request PR81

**Comment by raffienficiaud** [comment] 2016-09-16 15:38
I do not have any proper translation for BUTA (eg. http://www.urbandictionary.com/define.php?term=Buta ... ) but if you need something, let me know. There is still some time to include changes in 1.62, especially for the doc.

Thanks,
Raffi

**Comment by guwirth** [comment] 2016-09-16 15:40
BUTA = Boost Unit Test Adapter :-)

**Comment by raffienficiaud** [comment] 2016-09-16 15:43
:) The API for loggers has changed but I made it so that it is backward compatible. There might be an issue with the way you parse the datasets though, as now the declaration itself creates a test-suite filled with test-cases.

**Comment by guwirth** [comment] 2016-09-16 17:32
@raffienficiaud we are parsing the DOT and XML files. Are there any changes?

Last time we had problems to detect different versions because there were no version numbers in the files. If there are still no version numbers in the files a proposal is to add one to DOT and XML output and increase it with any incompatible chance.

**Comment by raffienficiaud** [comment] 2016-09-16 18:06
True. If there is something like this that bugs you, I believe the best thing would be to add a feature request on our backlog: https://svn.boost.org/trac/boost/query?status=assigned&status=new&status=reopened&component=test&col=id&col=summary&col=status&col=type&col=milestone&col=component&order=priority&report=52. 
I'll try to address that in a lively manner. 1.62 is closed for this kind of improvements, it is likely that it goes to 1.63.

BTW, doesn't the XML output contain the BOOST_VERSION if the build_info are requested?

**Comment by sergegers** [comment] 2016-09-30 18:58
So, there is no 1.62 support yet? 
@raffienficiaud I think it will be a good idea to interact with BUTA guys before the breaking changes introduction.

**Comment by raffienficiaud** [comment] 2016-10-01 06:58
@sergegers What do you mean? everything is backward compatible from a user perspective.

**Comment by guwirth** [comment] 2016-10-01 07:07
> there is no 1.62 support yet? 

@sergegers we don't know because we did not test it. Did you test the latest version with 1.6.2? Are there any problems?

You can download a snapshot frome here: https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter/branch/master/job/8c3p7ruudq92q4nm/artifacts

**Comment by sergegers** [comment] 2016-10-01 07:43
@raffienficiaud No it doesn't. Try to ask yourself how do the customers use XML output? They process it by some tools or scripts. If I upgrade to a new version and output is suddenly changed I call it breaking change.

**Comment by sergegers** [comment] 2016-10-01 07:50
@guwirth All tests are failed with message: "Boost Test result file was not found or is empty."

**Comment by raffienficiaud** [comment] 2016-10-01 08:06
@sergegers where can I see those tests?

**Comment by sergegers** [comment] 2016-10-01 09:19
@raffienficiaud Problem is not in tests, the problem is in XML format change.

**Comment by raffienficiaud** [comment] 2016-10-01 10:30
@sergegers what makes you think that the xml format has changed?

**Comment by netspiri** [comment] 2016-10-03 06:53
So... I did (very) quick run of BUTA with Boost 1.62 and these are some quick observations:

Pros:
- As listed in the change log, `BOOST_DATA_TEST_CASE` tests are now listed as individual tests in list content output allowing execution of individual test cases. Thanks @raffienficiaud.
- As listed in the change log, `BOOST_DATA_TEST_CASE` tests source file information is now listed correctly. Thanks @raffienficiaud.

Cons:
- As stated by @sergegers, it is not possible to execute *any* test cases. :disappointed:.

Problem seems to stem from our use of command-line arguments. This is a sample command-line arguments we use: 
```
"--run_test=test_case_arity1_implicit/_0" "--log_format=XML" "--log_level=test_suite" "--log_sink=C:\Users\<User>\AppData\Local\Temp\Misc.test.boostd.exe.5788.6.test.log.xml" "--report_format=XML" "--report_level=detailed" "--report_sink=C:\Users\<User>\AppData\Local\Temp\Misc.test.boostd.exe.5788.6.test.report.xml" > "C:\Users\<User>\AppData\Local\Temp\Misc.test.boostd.exe.5788.6.test.stdout.log" 2> "C:\Users\<User>\AppData\Local\Temp\Misc.test.boostd.exe.5788.6.test.stderr.log"
```

Running manually from the command-line using the same command-line format, the test runner is breaking with the following error listed in stderr:

```
Test setup error: Access with invalid type for argument corresponding to parameter log_sink
```

Removing the `--log_sink` argument (temporarily for testing) later breaks with:

```
Boost.Test framework internal error: unknown reason
```

Removing both the `--log_sink` and `--report_sink` arguments (temporarily for testing) leads to proper execution.

When I have more time, I may take a good proper look at this but it does not seem to be anytime in the near future. Suggestions/Guidance are very much appreciated.

**Comment by raffienficiaud** [comment] 2016-10-03 14:17
I isolated the problem and is due to a cast to an erroneous type on boost.test side (this is obviously a bug). I will fix that tonight, but in the meantime it means that 1.62 is messed on my side. As a workaround, would you please try with the `--logger` interface just to check if it would work better for the `log_sink` ? (the `--report_sink` will not work in any case).

The good thing in this story is that 1.63 is targeted sooner than end of year. Do you ship boost.test with your BUTA?

**Comment by sergegers** [comment] 2016-10-03 15:14
@raffienficiaud Sorry for my suspicions in evil intentions to change XML format. But there is a third case I know when a new Boost.Test version breaks BUTA. The first was  a output that became an invalid XML document, the second was a switch rejecting lowercase value. May be consider an option to include a BUTA check in final development stage before deploying? It takes a couple of minutes.

**Comment by raffienficiaud** [comment] 2016-10-03 15:23
@sergegers no worries, and sorry for the bug. I currently do not have a good coverage of the command line interface. Integrating the BUTA checks is definitely something I (or we) need to look at.

**Comment by sergegers** [comment] 2016-10-08 17:10
@raffienficiaud If you fix the adapter error could you create a patch before boost 1.63 will be issued?

**Comment by netspiri** [comment] 2016-10-27 15:14
Just a small update regarding this issue. Currently working on it  (https://github.com/netspiri/vs-boost-unit-test-adapter/commits/fix/%23158) and found a workaround for the `--log_sink` argument. `--report_sink` is definitely trickier - I cannot see other options at the moment other than to redirect the report output to stdout/stderr and extract the content from there.

**Comment by guwirth** [comment] 2016-10-31 09:53
> I cannot see other options at the moment other than to redirect the report output to stdout/stderr and extract the content from there.

@netspiri in the past we had the problem that applications writing also to stdout/stderr were creating invalid log files? Is your workaround able to handle this scenario?

**Comment by raffienficiaud** [comment] 2016-11-02 13:13
@sergegers Fixed in develop. The related branch is [topic/12507-broken-report-sink](https://github.com/boostorg/test/tree/topic/12507-broken-report-sink), rev 5d5c3e46f38e1a7fe92dfe2a554e5abcb8431481. Should be in 1.63.

**Comment by sergegers** [comment] 2016-11-03 16:08
@raffienficiaud I overwrite 1.62 test folder with your fix rebuild boost and my projects and still have no effect.

**Comment by raffienficiaud** [comment] 2016-11-04 15:08
@sergegers I am a bit surprised. Would you please indicate the command line and the observed behaviour?

**Comment by MatrixManAtYrService** [comment] 2016-11-07 00:40
I'm running across this as well.  If there's anything I can do to help, please let me know.

**Comment by netspiri** [comment] 2016-11-07 13:13
I have just downloaded the boost test [topic/12507-broken-report-sink](https://github.com/boostorg/test/tree/topic/12507-broken-report-sink) branch (commit `5d5c3e46f38e1a7fe92dfe2a554e5abcb8431481`) and I can confirm that BUTA works with the mentioned fix without the need to make use of the workaround presented in #164. Thanks @raffienficiaud for the fix.

Just a re-cap of what I did (feel free to correct me if I did something wrong):
- Download Boost 1.62
- Download the topic branch of Boost Test
- Replace the contents of the Boost 1.62 `boost/test` with the ones from the topic branch
- Replace the contents of the Boost 1.62 `libs/test` with the ones from the topic branch
- `bootstrap.bat`
- Compile Boost 1.62 with the fix
- Adapt a test project with use the topic's include directory and the static library output
- Compile project. At this point, BUTA successfully discovered the project's test using `--list_content=DOT`.
- Run a test from BUTA. Test runs and passes/fails as expected (i.e. no more "Boost Test result file was not found or is empty." error).

**Closed** 2016-11-07 20:00 UTC
Labels: enhancement

**Comment by raffienficiaud** [comment] 2016-11-08 22:56
@netspiri thanks for the report!
