### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by swc9fe** [etas/vs-boost-unit-test-adapter#207] opened 2017-07-03 06:19 UTC
Hi,

With the version 1.0.9.25 of the Boost Unit Test Adapter I'm able to see all unit tests in my solution (VS2015, Boost 1.59) while being in the Debug configuration. However, it takes approx. 20 Minutes to see all unit tests in the adapter. Before that, I'm not able to launch any already displayed unit test...

I have 218 projects in my solution with 2190 unit tests. While I was using an older version of the unit test adapter I had the problem that I had to restart the visual studio (maybe several times) to get all unit tests displayed, but displaying the tests was much faster...

**Comment by guwirth** [comment] 2017-08-21 08:13
@netspiri had a short look with Process Monitor which actions are executed for each .vcxproj to **discover tests**.
* There is several times the command line called to log the errors to a file `...2>...`. Strange why this is called so often?
* Finally the Boost test application is called again several times `... -list_content=DOT`.
* think this many calls are eating up the time

Wondering why we are not calling this only once during the step **discover tests** per boost test binary?

**Comment by netspiri** [comment] 2017-08-25 09:03
Allow me to clarify @guwirth post. The test module is only executed once. Process Monitor just happens to list all instances of activity done by the module such as opening a file, writing and closing the file.

We will be looking further into this and applying some thoughts we had been discussing internally. As of right now, our approach to optimise this is:
- Selectively merge particular commits from the Microsoft [fork](https://github.com/Microsoft/vs-boost-unit-test-adapter), specifically the ones which replace Visual Studio interaction. Early tests show that this is generally faster (and safer and cleaner) than our current approach of hooking with the COM object.
- Parallelise discovery across threads much like [Google Test Adapter](https://github.com/csoltenborn/GoogleTestAdapter).
- Reduce output from the 'Test' pane. In the past, we have noted that this does affect performance ever so slightly. Note that this output will not be removed, just logged to the output log file and not the 'Test' pane.

**Comment by guwirth** [comment] 2017-08-25 10:43
Hello @netspiri thanks for your investigation.
* makes sense to align code with Microsoft fork to have it easier to exchange code
* Were you able to profile the code to find the bottleneck? Are these points above only guesses or measured in reality?

**Comment by netspiri** [comment] 2017-08-29 06:17
Hi @swc9fe,

@guwirth and us had a meeting regarding this issue to better understand the situation at hand. If you do not mind, allow me to focus on this particular sentence:

> Before that, I'm not able to launch any already displayed unit test...

If I understand correctly, this means that tests in the test explorer window are being listed, yet, during the process of listing, it is not possible to run them. Is my understanding of this correct? Is the issue related to the fact that discovery needs to cater for all of the available modules before the test explorer window becomes responsive?

Should this be the case, we would like to request, if possible, feedback should the same occurs on Visual Studio 2017. From an adapter point of view, both this and the Microsoft fork are pretty much identical but the IDE is generally more responsive and the [vstest](https://github.com/microsoft/vstest) Framework (by which the adapter is used) has had a major revamp. Internal tests show that discovery speeds have improved from Visual Studio 2015 to Visual Studio 2017 by approximately 1 minute for the same solution consisting of around 91 test projects.

It would be very helpful for us if you could provide feedback so that we can better identify the problem at hand and focus our efforts on the current issues.

**Comment by swc9fe** [comment] 2017-08-30 04:22
Hi netspiri,

Yes, you’re right. While the test explorer is busy listing all tests, the already displayed ones cannot be executed. So, I have to wait until the test explorer is idle again and all tests are displayed (which takes approx. 20 Minutes). Only then I can launch the tests.

Unfortunately Visual Studio 2017 is not installed on my machine (and for now, this is not planned either), so I cannot give feedback regarding differences between both versions.

Best regards
Christian Schwegmann

Von: netspiri [mailto:notifications@github.com]
Gesendet: Dienstag, 29. August 2017 08:17
An: etas/vs-boost-unit-test-adapter <vs-boost-unit-test-adapter@noreply.github.com>
Cc: Schwegmann Christian (ETAS/EHE1) <christian.schwegmann@etas.com>; Mention <mention@noreply.github.com>
Betreff: Re: [etas/vs-boost-unit-test-adapter] Low Performance (#207)


Hi @swc9fe<https://github.com/swc9fe>,

@guwirth<https://github.com/guwirth> and us had a meeting regarding this issue to better understand the situation at hand. If you do not mind, allow me to focus on this particular sentence:

Before that, I'm not able to launch any already displayed unit test...

If I understand correctly, this means that tests in the test explorer window are being listed, yet, during the process of listing, it is not possible to run them. Is my understanding of this correct? Is the issue related to the fact that discovery needs to cater for all of the available modules before the test explorer window becomes responsive?

Should this be the case, we would like to request, if possible, feedback should the same occurs on Visual Studio 2017. From an adapter point of view, both this and the Microsoft fork are pretty much identical but the IDE is generally more responsive and the vstest<https://github.com/microsoft/vstest> Framework (by which the adapter is used) has had a major revamp. Internal tests show that discovery speeds have improved from Visual Studio 2015 to Visual Studio 2017 by approximately 1 minute for the same solution consisting of around 91 test projects.

It would be very helpful for us if you could provide feedback so that we can better identify the problem at hand and focus our efforts on the current issues.

**Comment by guwirth** [comment] 2017-08-30 06:22
team 1 / project 1:
* one solution containing test projects only
* all 90 projects follow the naming convention: *.test.boostd.exe
* Boost 1.61
* 4192 unit tests
* no runsetting files
* size of EXE 1...8 MB, some up to 14MB
* size of PDB 10...40MB, some up to 120MB
* time for discover tests: VS2015: 1min 47s / VS2017:  49s

**Comment by guwirth** [comment] 2017-08-30 06:55
team 2 / project 2 (@swc9fe, @esj1fe):
* one solution containing test projects **and** productive code
* 218 projects some follow the naming convention: *.test.boostd.exe, some not
* Boost 1.59
* 2190 unit tests
* no runsetting files
* size of EXE 2...30 MB, about 1/3 70MB to 100MB
* size of PDB 20...500MB; most > 100MB
* time for discover tests: VS2015: 20min / VS2017:  ?

**Comment by guwirth** [comment] 2017-09-04 15:19
team 2 / project 2:
* with **VS2017** and Boost.Test adapter **1.0.8.1** it takes "only" about 2 minutes.
* we will try with **VS2015** & **1.0.9.28** Boost.Test adapter

**Comment by guwirth** [comment] 2017-09-05 06:24
@netspiri & @LukaszMendakiewicz see updated comments above.

**Comment by guwirth** [comment] 2017-09-06 19:01
@netspiri 

team 2 / project 2: faster with 1.0.9.28 (about 5 minutes) but does not detect all tests. Think it is because of Boost 1.59 and because not all EXE follow the naming rule *.test.boostd.exe. Maybe we can try again after merging your 3 PR.

**Comment by guwirth** [comment] 2017-09-07 13:31
@netspiri 

team 2 / project 2: again slower with 1.0.9.34 (about 8 minutes), find more tests but still not all.
Still think next try should be the Google.Test approach to find Boost.Test executables.

**Comment by guwirth** [comment] 2017-10-20 07:38
We have now two solutions with #216 and #217 which has nearly same performance. So question is with which one we should continue? Which one is easier to maintain in future?

* I tend to align it with Google Test Adapter because this solution doesn't need debug information files?
* String in binaries are more stable then symbol names?

@netspiri what are you thinking?
@LukaszMendakiewicz do you also have an opinion to this?

team 1 / project 1:

    one solution containing test projects only
    all 90 projects follow the naming convention: *.test.boostd.exe
    Boost 1.61
    4665 unit tests
    no runsetting files
    size of EXE 1...8 MB, some up to 14MB
    size of PDB 10...40MB, some up to 120MB

    Replace debug symbol lookup with Boyer Moore search 1.0.9.36
        VS2015: Discover test finished: 4665 found (0:01:06,1742027)

    Cache Boost.Test Symbols for Improved Performance 1.0.9.35
        VS2015: Discover test finished: 4665 found (0:01:05,3178651)

team 2 / project 2:

    one solution containing test projects and productive code
    218 projects some follow the naming convention: *.test.boostd.exe, some not
    Boost 1.59
    2190 unit tests
    no runsetting files
    size of EXE 2...30 MB, about 1/3 70MB to 100MB
    size of PDB 20...500MB; most > 100MB
    time for discover tests: VS2015: about 2 minutes

    Replace debug symbol lookup with Boyer Moore search 1.0.9.36
        VS2015: Discover test finished: 2190 found, about 2 minutes

    Cache Boost.Test Symbols for Improved Performance 1.0.9.35
        VS2015: Discover test finished: 2190 found, about 2 minutes

**Comment by guwirth** [comment] 2017-10-23 08:41
@netspiri https://github.com/Microsoft/vs-boost-unit-test-adapter/issues/9

With the "cache" approach, what is the time to build the cache? I presume the cache is maintained only for the duration of Visual Studio session, so needs to be rebuilt every time a solution is opened?

**Comment by netspiri** [comment] 2017-10-23 09:04
The cache is just a map/dictionary which is populated when a request for a new Boost.Test runner instance is requested. The intention was that the cache is populated when the discoverer factory tests for the `--list_content` capability and retained for later use by the `ListContentDiscoverer` to query the `--version` capability. This allows us to avoid a secondary symbol lookup within one `DiscoverTests` invocation.

As far as cache retention, going back through my changes, it seems that the cache is retained until the test execution framework exists. This might cause some unintended side effects but as an alternative, we can limit the cache for `DiscoverTest` invocations as intended i.e. create a Boost.Test runner cache when `DiscoverTest` is called.

The intention of the cache was not to speed up execution time across `DiscoverTest` invocations, but to improve the performance of each individual `DiscoverTest` invocation.

**Comment by netspiri** [comment] 2017-10-23 09:57
PR #216 updated to reflect the original intention as described in the previous post.

**Comment by LukaszMendakiewicz** [comment] 2017-10-23 14:53
Why not speed up execution across `DiscoverTest` invocations as well? You might use file modification time stamp for the cache invalidation mechanism. Are the gains too little to be worth the added complexity?

Is "string search" approach orthogonal to caching, i.e. could "string search" use some cache of its own to speed it up even further within one `DiscoverTest` invocation?

**Comment by netspiri** [comment] 2017-10-23 15:46
Hi @LukaszMendakiewicz,

We can consider caching across `DiscoverTest` invocations but I do not know if it will be beneficial. If I recall correctly, `DiscoverTests` is called only when a project is (re-)built or a solution is opened anew, meaning that we do not need to actually cater for this on our end. I may be wrong on this one and it would be great if we can clear this out.

Regarding 'string search' and 'caching', yes they are orthogonal. PR #217 builds on the caching mechanism of PR #216 since the cache is applied on the Boost.Test runner factory. Regardless of the capability identification method, any state stored by a Boost.Test runner will be available to other parts of the code as long as the same caching factory is reused. What this means is that when capabilities are identified for the first time, consequent invocations will avoid rummaging through file data.

**Comment by guwirth** [comment] 2017-10-23 15:48
@netspiri & @LukaszMendakiewicz my favourite is still to align with Google Test approach:
* nearly same performance, less complex
* easier to maintain: especially if Google Test & Boost Test are maintained by same person
* working without symbol files: do not need to access these huge .pdb files
* seems to be more stable: strings in binary are changing not so often then symbol names

**Comment by guwirth** [comment] 2017-10-26 13:16
@netspiri & @LukaszMendakiewicz: for me #217 is the favourite

**Comment by LukaszMendakiewicz** [comment] 2017-10-26 16:17
No objections from me :).

**Comment by guwirth** [comment] 2017-10-28 08:04
addressed by #217

**Closed by guwirth** 2017-10-28 08:04 UTC
Labels: bug
