### ISSUE TITLE
--list_content option failed

### ISSUE THREAD

**Issue by sergegers** [etas/vs-boost-unit-test-adapter#182] opened 2017-01-27 23:32 UTC
It seems to impossible to properly set the list content option. If .runsettings file is used Test Settings File preset could be easily  reset to the default state (after IDE crash or simple after restart). It's a Visual Studio bug. There is a way to enable option by changing the test execution file extension to .test.boostd.exe according to the User Manual but it doesn't work for me (bug?).
So, Is there a way to get a stable BUTA configuration?

PS. Since the last adapter issue test case with the decorator expected_failures() seems to get failed under any configuration.

VS 2015 U3, Boost 1.63

**Comment by netspiri** [comment] 2017-01-30 11:21
Hi @sergegers and many thanks for the feedback.

To be honest I have not fully grasped the issue at hand. Are you referring to the `<ForceListContent>` configuration option? And with which version of the adapter are you facing such issues? Is it possible to clarify these and possibly attach the log file of the adapter please?

The latest versions should only make use of `--list_content=DOT` and failing to achieve this, tests are not discovered. In such scenarios, we recommend that you try and execute the test executable from the command line as follows: `test.exe --list_content=DOT` to ensure that it actually works. We have encountered issues in the past that test modules were failing due to missing DLLs or incorrect working directory.

In any case, the following should address some of your concerns hopefully.

- Re: Use of `.runsettings`

Unfortunately, the issues you mention are also reproducible on our end. I do not think this is something we can fix from the adapter's end though. The only way I have managed to force a `.runsettings` change is to trigger a complete rebuild of the current solution.

- Re: `.test.boostd.exe` extension

In order to set this, our usual approach is the following:

![extension](https://cloud.githubusercontent.com/assets/6962427/22416787/e700cf1c-e6d0-11e6-8af3-2c106c13c7c9.png)

This is confirmed to work as expected with the latest version available from the `master` branch.

- Re: `expected_failures()`

To be honest, we did not cover this feature much since we do not use if often in our test scenarios. I will investigate this further and provide feedback soon(-ish).

**Comment by sergegers** [comment] 2017-01-30 12:24
@netspiri Thank you for response. At first I'll try to clarify my initial post.

If I understand correctly there is two ways of parsing test project:
- the old scenario: parse a source code. This is the way that supports a some base functionality;
- the new scenario: grab "metainformation" through the boost.test --list_content option that provides a more information about the tests.
I decided to use the latter one.

1. The .runsettings file scenario. 
I wanted to enable <ForceListContent> option and made it using runsettings file. Visual Studio is often reset runsettings file assignment. According to stackoverflow it's a VS bug since 2010. As a workaround I select another approach mentioned in the manual.
2.  I modify output executables for test projects as *.test.boostd.exe. There were no visible effect. The VS "Tests" output window recommend me to enable --list_content option.

So the questions I have:
1. Is it correct: the boost.test predicates are supported only through --list_content option. More common what the difference in using or not using this option?
2. The current state of predicate support:
- what predicates are supported;
- what predicates are supported but support is broken now due the bugs.

My further steps:
Now I'm using the BUTA version downloaded from marketplace, VS 2015 U3, boost 1.63. Can I download the last master version?
If I remember correctly I hung the debugger on breakpoint to get a log files. Is where a more convenient way to get them?

**Comment by netspiri** [comment] 2017-01-30 13:24
Many thanks for the clarification @sergegers.

Key point is the use of the Boost Adapter available from the Visual Studio marketplace. The version available there does not contain the `.test.boostd.exe` convention so that is why it is not working for you. The new release should be up soon (stay tuned). For further reference, I resurrected issue #171 to keep things in perspective as we approach the 1.0.8.X release. In addition, there were some other fixes related to said area so I would recommend you avoid forcing `--list_content` unless necessary.

If you want a quick-fix, downloading the in-development build through [AppVeyor](https://ci.appveyor.com/project/guwirth/vs-boost-unit-test-adapter) should be a good solution. Refer to [Downloading a Development Build](https://github.com/etas/vs-boost-unit-test-adapter/wiki/Continuous-Integration-AppVeyor#downloading-a-development-build) in the Wiki for more details.

Regarding the remainder:

- Re: Support for Predicates

Currently we only provide explicit support for the `label` decorator since that allows for categorization. The other decorators (e.g. `expected_failures`) are only supported implicitly i.e. we do not have explicit logic to deal with them. Just tested the latest `master` version and `expected_failures` should work as expected i.e. tests are marked as passed as long as the `expected_failure` count matches.

- Re: Log Files

The 'Test' output pane should contain a line similar to the following:

```
Logger initialized. Logging to C:\USERS\<user>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\ETAS GMBH\BOOST UNIT TEST ADAPTER\<version>\BoostTestAdapter.dll.log
```

That file should be retained after test execution and you should be able to locate all the details. If you fail to find the file, the content of the 'Test' pane should at least aid for debugging.

**Comment by sergegers** [comment] 2017-01-30 21:47
@netspiri almost all works as expected with the master release version. 
- all tests are correctly discovered; 
- decorator enable_if is supported. 

The decorator expected_failures() displays the test as failed though. I attached the expected failures log file, but there nothing interesting at all in it and the detailed reports referenced in it had been already deleted after the test was done.

[BoostTestAdapter.dll.txt](https://github.com/etas/vs-boost-unit-test-adapter/files/740481/BoostTestAdapter.dll.txt)

**Comment by netspiri** [comment] 2017-01-31 06:44
Hi @sergegers,

Do you have sample test code which we can use to reproduce the issue please?

As with regards to the logs, yes we do not log test results. Maybe we can consider this as a possibility for improvement. Thanks for the feedback.

**Comment by netspiri** [comment] 2017-01-31 07:03
I have been trying to reproduce the issue using the following with my local working copy of the adapter, VS2015 U2, Boost 1.63:

```c++
// Test Result: Passed
BOOST_AUTO_TEST_CASE(ExpectedFailureDecoratorTest1, *utf::expected_failures(1))
{
	BOOST_CHECK(false == true);
}

// Test Result: Failed
BOOST_AUTO_TEST_CASE(ExpectedFailureDecoratorTest2, *utf::expected_failures(1))
{
	BOOST_CHECK(false == true);
	BOOST_CHECK(false == true);
}

// Test Result: Failed
BOOST_AUTO_TEST_CASE(ExpectedFailureDecoratorTest3, *utf::expected_failures(1))
{
	BOOST_REQUIRE(false == true);
}
```

Resultant test results seem fine in my opinion. If I am interpreting this incorrectly, please let me know.

**Comment by sergegers** [comment] 2017-01-31 10:01
Sorry, that's my fault. The exception is raised in failed test instead of the wrong result.

**Comment by netspiri** [comment] 2017-01-31 10:04
Could you kindly clarify please:

> The exception is raised in failed test instead of the wrong result.

**Comment by sergegers** [comment] 2017-01-31 10:12
The tested function throws exception instead of returning wrong result. The right checking method must be  BOOST_CHECK_THROW() or something like this.

**Comment by netspiri** [comment] 2017-01-31 10:31
So...

```c++
namespace
{
	void foo()
	{
		throw std::runtime_error("foo");
	}

	void bar()
	{
		// no throw
	}
}

// Test Result: Passed
// Message: "Test case ExpectedFailureDecoratorTestNoThrow has fewer failures than expected"
BOOST_AUTO_TEST_CASE(ExpectedFailureDecoratorTestThrow, *utf::expected_failures(1))
{
	BOOST_CHECK_THROW(foo(), std::runtime_error);
}

// Test Result: Passed
// Message: "exception std::runtime_error expected but not raised"
BOOST_AUTO_TEST_CASE(ExpectedFailureDecoratorTestNoThrow, *utf::expected_failures(1))
{
	BOOST_CHECK_THROW(bar(), std::runtime_error);
}

// Test Result: Failed
// Message: "class std::runtime_error: foo"
BOOST_AUTO_TEST_CASE(ExpectedFailureDecoratorTestWithThrow, *utf::expected_failures(1))
{
	foo();
}
```

I tested the above scenarios with the above results and they match with output as running the tests from the command line.

Apologies for the lengthy resolve to the issue, but at this point I would prefer having a sample test scenario which I can run locally to avoid further misunderstandings.

**Comment by sergegers** [comment] 2017-01-31 11:20
@netspiri test result looks complying to boost.test specification and I have the same result on my side.

**Comment by netspiri** [comment] 2017-01-31 11:48
@sergegers So can this issue be considered as resolved? If so, kindly requesting to close the issue. Thanks in advance.

**Comment by sergegers** [comment] 2017-01-31 11:56
@netspiri Yes. I think so.

**Closed** 2017-02-03 15:56 UTC
Labels: question
