### ISSUE TITLE
Side effect of executing all executables after a successful build

### ISSUE THREAD

**Issue by SimonLux** [etas/vs-boost-unit-test-adapter#88] opened 2016-01-20 17:02 UTC
I noticed that the te.processhost.managed.exe executes all executables that are built by projects in the solution with the command line option "--help" after each successful build. This can lead to side effects depending on what those executables do.
Example:
Imagine what happens if I build a project that creates an .exe which has the purpose to format all hard disks.

**Comment by guwirth** [comment] 2016-01-20 21:26
duplicate #87

**Comment by netspiri** [comment] 2016-01-21 06:50
Hi @SimonLux,

Could you kindly state the adapter version you are using and any configuration in use please? `--help` should only be issued when using the experimental list-content discovery mode which is disabled by default in the recent 1.0.6.20 release.

We understand your concern regarding executing possibly malicious exes. Our approach to this is to verify against the debug symbols to make sure that the module is a BOOST test module if a given symbol is available. It is only then that we move onto using the `--help` argument. Given that this feature will be improved in the next release, we will still consider using the debug symbols to guard from malicious content.

@guwirth Although this might be a duplicate of #87, I think both issues are arguing for 2 distinct concerns. Solving #87 can help to mitigate this issue but we still need a viable guarding mechanism in case users do not provide a configuration file and attempt to use `--list_content` which should be the default in the next version.

**Comment by SimonLux** [comment] 2016-01-21 07:34
Hi @netspiri,

I'm using 1.0.6.20 from the Visual Studio Gallery  without a testsettings file.
I noticed this issue only because a project that is contained in one of my solutions pops up a dialog if not called with proper command line options. Process Monitor showed that te.processhost.managed.exe calls it with the command line option "--help".

@guwirth: I agree with @netspiri that #87 addresses a feature request and #88 addresses a problem.

**Comment by daniel-kun** [comment] 2016-01-21 07:47
As the original author of #87, I think that these issues are separate, too. With implementing #87 you can solve the problem of #88, but a) you have to first notice it and b) you have to know that feature #87 exists and how to use it. If I understand correctly, as soon as `--list_content` is implemented and is the default, .exe that are not boost unit tests will not be run. Hence I'd see this issue as resolved then.
(On an unrelated side note: I find the documentation of the Boost Unit Test Adapter *extremely* well done and thorough! Compliments on that)

**Comment by guwirth** [comment] 2016-01-21 08:46
>  to this is to verify against the debug symbols to make sure that the module is a BOOST test module

@netspiri Still think that it is the wrong approach to use debug symbols.Typical PDB files (especially with boost) are 100 MB or larger. Loading the EXE with PDB always twice (once with `--help`, once with `--list_content`) is much too slow. We should look for another way:
* maybe there is an API to detect that project is a test project?
* or scan vcxproj to detect what is a test project
* or add a symbol to stdafx.h to enable functionality
* ...

And as always: Would be interesting to know how others are doing it. Our projects are always mixed (boost test & nunit). How is nunit doing it?

> If I understand correctly, as soon as --list_content is implemented and is the default, .exe that are not boost unit tests will not be run. 

@daniel-kun my understanding is that you always have to start the EXE to find out that it is a boost test executable. That is the point we want to avoid. There should be a way to know that the EXE is a boost test **before** the file is loaded and executed (see original description in #87). 

#87 and #88 has for me the same root cause: start only EXE containing boost tests? #87 is a proposal for a possible solution for #88?

**Comment by netspiri** [comment] 2016-01-25 07:37
@guwirth PDB files are not read multiple times. Launching a (debug) executable does not imply that the PDB files are parsed - it is up to the attached debugger to read the PDB files, and a debugger will only read PDB files when instructed. Visual Studio hides all of this but WinDBG should provide a better picture.

The only time we launch an executable with debug-attachment support is when a user selects 'Debug Selected Tests'. When launching the module for `--help` and `--list_content` we do not launch the process with the possibility to attach to it.

Additionally, our implementation of reading PDB files is done through the [dbghelp library](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679309(v=vs.85).aspx). All we request from the library is to perform a lookup for a *single* symbol and it is up to the implementation to identify the best way to retrieve said symbol. Depending on the PDB file, the implementation *may* resort to using functions such as `fseek` if the PDB file format provides an index of some sort. Again, given that we do not know the implementation, this is purely speculation. Further profiling is necessary to determine whether this is a bottleneck. Our initial `--list_content` implementation suffered because we had to read more than 1 symbol, and crossing the threshold from managed C# to the library's native nature was expensive. Fortunately, using `--list_content=DOT`, it should only require us to check for 1 symbol just to make sure that the executable is a BOOST test module. Test source information is embedded inside the DOT output which should alleviate the dependency over the debug symbols.

Even after all of this discussion, let us not forget that there will always be this sort of case:

`BOOST_AUTO_TEST_CASE(VeryMaliciousTest) {
    FormatDrive();
    BOOST_CHECK(DriveContentsIsEmpty());
}`

which unfortunately, we cannot guard against.

Regarding NUnit, as noted in issue #81:

> As an additional note, although we appreciate the comparison to the NUnit adapter, please note that the way the NUnit adapter works is by using reflection. The adapter can identify tests and execute them without the need to launch any additional processes. This technique is, unfortunately, not available and not easy to simulate for native BOOST tests.

As mentioned earlier, solving issue #87 and providing and an additional defence mechanism (being via debug symbols or otherwise) should suffice to cater for this issue.

**Comment by guwirth** [comment] 2016-03-19 08:58
@SimonLux please do some testing with #109

**Closed** 2016-03-22 06:50 UTC
Labels: enhancement, solution available
