### ISSUE TITLE
BOOST_DATA_TEST_CASE appears as _0, _1… on the test list

### ISSUE THREAD

**Issue by mwu-tow** [etas/vs-boost-unit-test-adapter#181] opened 2017-01-26 16:41 UTC
Hi,
please consider the have the following code:
```
#include <boost/test/auto_unit_test.hpp>
#include <boost/test/data/test_case.hpp>
#include <boost/test/data/monomorphic.hpp>

static const std::vector<int> sectorCounts{ 8, 12, 24, 32 };

BOOST_DATA_TEST_CASE(BoostUnitTest, boost::unit_test::data::make(sectorCounts), sectorCount)
{}
```

The Test Explorer shows me 4 test cases named _0, _1, _2, _3. 
![image](https://cloud.githubusercontent.com/assets/1548407/22340462/daa69d0e-e3ed-11e6-9045-af92c021b7b9.png)

I use:
* Visual 2015 Update 3
* Boost 1.63
* latest BUTA from the repo( e4e374fd4fe80b68100fac67460a8cf694ba16ed )

**Comment by netspiri** [comment] 2017-01-27 07:24
Hi @mwu-tow and many thanks for the feedback.

That is expected behavior. As of Boost.Test delivered in Boost 1.62, Boost.Test outlines individual data test cases as tests under a test suite with the name of the `BOOST_DATA_TEST_CASE`. The representation you see there maps one-to-one with the output of `--list_content(=DOT)`.

Should you switch the category type to 'Traits' you should find this easy to identify.

Fair to say that we should not force users to use a specific category type, so I am willing to close an eye on the one-to-one mapping and adapt the names of such test cases for test adapter users.

Feedback would be greatly appreciated.

**Comment by mwu-tow** [comment] 2017-01-30 13:39
Hi @netspiri,
thank you for the answer, it makes clear what is happening. 

Indeed using Traits grouping mode allows to see data-generated test subcases grouped under the main name. However, there are a few drawbacks to this workaround:
1. User is forced to use Traits grouping mode in order to see meaningful names for data test cases. (workaround: hovering cases with mouse and checking the tooltip works everywhere)
2.  The data test cases cannot be searched by their name — filtering only supports the "leaf node" names (like `_1` and so on). 
3. It breaks the logic of grouping test cases by their TestSuite — each data test case is treated as a separate TestSuite, while it logically belongs to other TestSuite.

I think the root of problem is that Visual Studio Test Explorer does not support nested tree-like hierarchies of tests and we are forced to flatten them to two-level list (I believe?). 
I wonder if there's something that can be done on BUTA's side to improve the experience. 

The actual test case id is something like `test_suite1/DataTestCase/_0` or `test_suite1/SimpleTestCase`. The current behavior is to treat everything up to the last slash as a test suite name. I think that it might be better to treat characters up to the *first* slash as a test suite name and everything after that as test case name.

For example, instead of having test `_0` in suite `test_suite1/DataTestCase` we would have `DataTestCase/_0` in suite `test_suite1`. I think that would solve the problems I described above. 

What do you think about that?

**Comment by netspiri** [comment] 2017-01-30 14:01
Hi @mwu-tow and many thanks for the response.

If I am understanding your perspective correctly, you would like to adapt the names such that they are more convenient to visually inspect or search.

Regarding point 3, I understand that `BOOST_DATA_TEST_CASE`s are rendered differently, but given our one-to-one approach we opt for what Boost.Test provides. I believe that Boost.Test describe tests in this fashion to allow users to execute individual test cases out of a `BOOST_DATA_TEST_CASE`.

You are right-on-point regarding Visual Studio's test representation - we manually flatten the hierarchy for Visual Studio use. Although we flatten the test cases, you should still be able to search using test suites (but the search criteria are rather archaic in my opinion). Typing: `Trait:"SuiteLevel1/SuiteLevel2"` in the search box will show tests which are within the `SuiteLevel2` test suite (child of the `SuiteLevel1` test suite) and its child test suites. This should alleviate some of your concerns.

Regarding the issues itself, I have been dabbling with some experiments locally but my major concern is that this will slightly affect the experience (for users utilizing the adapter through Visual Studio but more drastically for those who use the adapter through `vstest.console.exe`). I am willing to adapt for `BOOST_DATA_TEST_CASE` since it is a relatively new addition to Boost.Test and applying conventions earlier would be better, but I am more hesitant to apply changes to more 'stable' concepts.

**Comment by netspiri** [comment] 2017-02-03 15:23
@mwu-tow pull request #185 should have addressed some of your concerns. Does this new approach alleviate your concerns?

**Comment by guwirth** [comment] 2017-02-03 16:28
@mwu-tow I close this. Please reopen if there are still issues with 1.0.8

**Closed by guwirth** 2017-02-03 16:28 UTC
Labels: question

**Comment by mwu-tow** [comment] 2017-02-05 22:47
@netspiri 
Sorry for replying late and thank you for the fix.  I've just checked it with the official 1.0.8 build and it works as expected for me, resolving most of the problems. As we are forced to flatten the list, any choice has its own trade-offs and I understand that you prefer to keep to current convention.
