### ISSUE TITLE
Exception thrown when executing All Tests for Code Coverage having a runsettings file selected

### ISSUE THREAD

**Issue by gastart** [etas/vs-boost-unit-test-adapter#102] opened 2016-02-24 11:16 UTC
Using:
VS 2015 with Update 1
BUTA v1.0.7.77

An exception is being thrown when **Analyze code Coverage** and then selecting **All Tests** when having a valid **runsettings** file selected.

Executing:   -> [Suite1/Test1]
**Exception caught while running test batch** D:\TestProject\Bin\Win32\Debug\bin\Testing.BoostUnitTest.exe [Suite1/Test1] \(**Object reference not set to an instance of an object.**\)
Executing:   -> [Suite1/Test2]
**Exception caught while running test batch** D:\TestProject\Bin\Win32\Debug\bin\Testing.BoostUnitTest.exe [Suite1/Test2] \(**The process cannot access the file 'C:\Users\gastart\AppData\Local\Temp\Testing.BoostUnitTest.exe.test.stdout.log' because it is being used by another process.**\)
Executing:   -> [Suite1/Test3]
**Exception caught while running test batch**
D:\TestProject\Bin\Win32\Debug\bin\Testing.BoostUnitTest.exe [Suite1/Test3] \(**The process cannot access the file 'C:\Users\gastart\AppData\Local\Temp\Testing.BoostUnitTest.exe.test.stdout.log' because it is being used by another process.**\)

Please note the first error is different.

I did not personally troubleshoot the code, but the sharing violations are visible also via procmon.

**Comment by netspiri** [comment] 2016-04-20 15:54
Could not reproduce on trial installation of Visual Studio 2015 Enterprise Update 2.

**Comment by guwirth** [comment] 2016-05-21 08:38
@gastart not reproducible. We are closing it.

**Closed by guwirth** 2016-05-21 08:38 UTC
Labels: discussion, invalid
