### ISSUE TITLE
Log file not found, none of the found tests are run

### ISSUE THREAD

**Issue by antoncl** [etas/vs-boost-unit-test-adapter#82] opened 2016-01-10 08:13 UTC
When running the tests, an error is printed in the output window and no tests are run.

```
------ Run test started ------
Logger initialized. Logging to C:\USERS\ANTON\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\KTEANOCE.3A5\BoostTestAdapter.dll.log
Found test: Ast
Executing:   -> [Ast]
filestream was found to be null when handling path: C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml
Exception caught while running test batch C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe [Ast] (Could not find file 'C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml'.)
========== Run test finished: 0 run (0:00:05,9503403) ==========
```

**Comment by guwirth** [comment] 2016-01-10 08:25
Please try to run your boost unit test exe from the command line.
* Do you get results there?
* What is the return result of the exe?

One reason could be that your unit tests are buggy.

**Comment by antoncl** [comment] 2016-01-10 08:35
Yes, if I treat the executable as an ordinary executable I can both run and debug it.

```
C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug>CdefCompilerTes
ts.exe
Running 1 test case...

*** No errors detected
```

**Comment by antoncl** [comment] 2016-01-10 08:37
I believe there is some kind of mismatch between:

`BoostTestAdapter.dll.log` and `CdefCompilerTests.exe.test.report.xml`

It looks as if the logs are written into one file/location, but attempted to be read from another.

**Comment by guwirth** [comment] 2016-01-10 08:43
You can try with https://technet.microsoft.com/en-us/sysinternals/processmonitor to see where the report is written and where the adapter tries to read it. Start the tool and set a filter for the file name you are looking for.

**Comment by antoncl** [comment] 2016-01-10 09:01
Data is being written to: `C:\Users\Anton\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\kteanoce.3a5\BoostTestAdapter.dll.log`

File contents:
```
2016-01-10 09:54:32,941 [20108] INFO  Logger initialized. Logging to C:\USERS\ANTON\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\KTEANOCE.3A5\BoostTestAdapter.dll.log
2016-01-10 09:54:33,970 [20108] INFO  Found test: Ast/Ast01
2016-01-10 09:54:34,031 [20108] INFO  Executing:   -> [Ast/Ast01]
2016-01-10 09:54:34,415 [20108] ERROR filestream was found to be null when handling path: C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml
2016-01-10 09:54:34,416 [20108] ERROR Exception caught while running test batch C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe [Ast/Ast01] (Could not find file 'C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml'.)
```

The process monitor reports a failure to read: CdefCompilerTests.exe.test.report.xml
```
"Time of Day","Process Name","PID","Operation","Path","Result","Detail"
"09:51:28,8417890","te.processhost.managed.exe","11708","FASTIO_NETWORK_QUERY_OPEN","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","FAST IO DISALLOWED",""
"09:51:28,8418352","te.processhost.managed.exe","11708","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"09:51:29,1105415","te.processhost.managed.exe","11708","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: n/a"
"09:51:59,5424412","te.processhost.managed.exe","12660","FASTIO_NETWORK_QUERY_OPEN","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","FAST IO DISALLOWED",""
"09:51:59,5424888","te.processhost.managed.exe","12660","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"09:52:00,1395381","te.processhost.managed.exe","12660","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: n/a"
"09:54:34,0287881","te.processhost.managed.exe","20108","FASTIO_NETWORK_QUERY_OPEN","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","FAST IO DISALLOWED",""
"09:54:34,0288411","te.processhost.managed.exe","20108","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"09:54:34,4090952","te.processhost.managed.exe","20108","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: n/a"
"09:58:31,5000796","te.processhost.managed.exe","9360","FASTIO_NETWORK_QUERY_OPEN","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","FAST IO DISALLOWED",""
"09:58:31,5001227","te.processhost.managed.exe","9360","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a"
"09:58:32,2763746","te.processhost.managed.exe","9360","IRP_MJ_CREATE","C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml","NAME NOT FOUND","Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Open No Recall, Attributes: n/a, ShareMode: Read, AllocationSize: n/a"
```

**Comment by netspiri** [comment] 2016-01-11 09:31
Hi @antoncl,

First impressions seem to indicate that either the report file is not being created in the expected location by the BOOST test framework or it cannot be read by the adapter.

Could you kindly perform the following and report any findings please?

1. Open a command prompt and change directory to the location of the executable  
(e.g. `cd C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug`)  
2. Launch the test executable with the command-line parameters: `"--run_tests=Ast/Ast01" "--report_format=XML" "--report_level=detailed" "--report_sink=C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml"`  
(e.g. `CdefCompilerTests.exe "--run_tests=Ast/Ast01" "--report_format=XML" "--report_level=detailed" "--report_sink=C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml"`)

The mentioned procedure is a simplification of what the adapter uses to execute tests. This should allow us to better understand whether it is a file-writing issue or an issue with the adapter when reading the file.

P.S. If your test fixture has changed or any output files have been moved, please adapt the command line accordingly.

**Comment by antoncl** [comment] 2016-01-11 10:05
The command interpreter doesn't like the quotes around the individual parameters, here is what I got to work:

```CdefCompilerTests.exe run_tests=Ast/Ast01 --report_format=XML --report_level=detailed --report_
sink=C:\Users\Anton\Documents\Projects\libPerfCounter\src\Win32\Debug\CdefCompilerTests.exe.test.report.xml```

The output on std::out was:
```
Running 1 test case...
```

I've attached both std::err and the report file (renamed to a .txt file because of github limitations)


[err.txt](https://github.com/etas/vs-boost-unit-test-adapter/files/85530/err.txt)

**Comment by antoncl** [comment] 2016-01-11 10:08
I forgot to add the "xml" file (renamed to txt because github doesn't allow xml file uploads)

[CdefCompilerTests.exe.test.report.xml.txt](https://github.com/etas/vs-boost-unit-test-adapter/files/85535/CdefCompilerTests.exe.test.report.xml.txt)

**Comment by netspiri** [comment] 2016-01-11 10:15
HI @antoncl,

Thank you for the prompt response.

Noted that the issue was closed - is the test adapter still behaving the same i.e. reporting that the filestream is null? If so, please re-open the issue so that we will resolve it.

We will be looking into this further when we have the time, especially since you noted that the executable does not like the double-quotes around each parameter.

Note. Had a small typo in my last message. Should have been `--run_test` not `--run_tests`. The behaviour should be similar and the provided reports should be a good enough start for our analysis.

**Comment by antoncl** [comment] 2016-01-11 10:26
Hmm, I seem to have closed the issue accidentally. Right now I'm searching for the option to re-open it.

**Comment by candychiu** [comment] 2016-01-12 18:06
I encountered the same issue after upgrading to version 1.60.  I used to have 1.58, and it worked nicely.

**Comment by paumayr** [comment] 2016-01-12 20:18
I can confirm that this happens with boost 1.60 and works fine with 1.58.
When I debug a single test case, an exception is thrown which, when digging into the exception object leads to 'xml is not a valid enumeration value name for parameter log_format.'
![image](https://cloud.githubusercontent.com/assets/1908911/12275423/5def08b2-b970-11e5-9d71-dc64652141ed.png)

I don't know much about boost.test from an implementation side, but looking at the argv shows that --log_format=xml and --report_format=xml is passed to the test runner. changing the values to uppercase XML via the watch window (glad that XML is quite short ;) lets the test pass.

I guess this issue has to do with boost.test 3.1/1.60.0 improved command line interface as stated in the changelog: http://www.boost.org/doc/libs/1_60_0/libs/test/doc/html/boost_test/change_log.html

I'll look into supplying a patch to the test adapter.

**Comment by netspiri** [comment] 2016-01-13 06:36
Thank you very much @candychiu and @paumayr for your analysis!

**Comment by daniel-kun** [comment] 2016-01-15 11:08
I ran into the same problem, using Boost Unit Test Adapter from the VS Gallery - Version is 1.0.5.0. Is this supposed to be fixed in this version, or will the deployment to the VS Gallery happen later? If so, when can I expect it?

**Comment by netspiri** [comment] 2016-01-15 11:12
Hi @daniel-kun,

Issue should be fixed but the public release of 1.0.6.0 on the VS Gallery is yet to happen. Please follow issue #52 for further news on the subject.

**Comment by netspiri** [comment] 2016-01-19 07:01
Hi @antoncl,

Given the recent release of the Boost Unit Test Adapter, could you kindly update the extension and confirm whether the problem persists please?

**Comment by antoncl** [comment] 2016-01-19 07:31
@netspiri 

Yes, I just tested on all the projects/solutions where it failed. Everything seems to work fine now.

Thank you :-)

ps. Do you want me to close the question, or do you want the honors?

**Closed** 2016-01-19 17:33 UTC
Labels: question
