### ISSUE TITLE
V1.0.6: ... abort() has been called

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#69] opened 2015-11-25 10:23 UTC
If execution of Boost.Exe is crashing there will be a dialog:
```
Microsoft Visual Studio C++ Runtime Library
Programm: ...
abort() has been called
(Press Retry to debug the application)
```
Dialog is closing automatically after some seconds.

**Comment by netspiri** [comment] 2015-11-25 14:06
This issue is being caused in the discovery phase since `--list_content` executes the test executable. Dialog is closing automatically due to a timer mechanism which we use to ensure that the process does not remain executing indefinitely.

One possibility of why this issue is being caused is due to a failure during construction of global/static variables on program initialisation. In our tests, this issue can be reproduced when a global variable tries to reference a file which is not in the current working directory. Working directory issue is further detailed in issue #43.

**Comment by guwirth** [comment] 2015-11-25 19:42
Dialog should be suppressed and there should be a log file item instead.

**Comment by netspiri** [comment] 2016-04-20 08:44
@guwirth Is this issue still not resolved? We do not have access to `Boost.exe` on our end and cannot ensure that the latest version fixes the mentioned issue.

**Comment by guwirth** [comment] 2016-04-20 15:53
I think you can try this by writing a unit test calling `abort()` inside (http://www.cplusplus.com/reference/cstdlib/abort/). Think it is also interesting what happens if you call `exit()`(http://www.cplusplus.com/reference/cstdlib/exit/) or `terminate()` (http://www.cplusplus.com/reference/exception/terminate/).

**Comment by netspiri** [comment] 2016-04-21 09:14
Writing tests containing either of the 3 functions e.g.

```c++
BOOST_AUTO_TEST_CASE(abort)
{
	abort();
}
```

function accordingly i.e. test results are correctly generated and listed.

Having `abort` or `terminate` within a static context e.g.

```c++
struct Abort
{
	Abort()
	{
		abort();
	};
};

Abort s_abort;
```

will cause `--list_content=DOT` discovery to trigger the abort window shown earlier. Static/Global variables are constructed on program startup which will call the `Abort` constructor. The window will remain open depending on the `DiscoveryTimeoutMilliseconds` configuration option. Tests from said module will not be listed. I do not think we are in a position to properly identify, handle or log such behavior in the adapter. I think that if the test module causes this kind of error, I think it is the responsibility of the user/developer to correct said error using regular debugging techniques.

**Comment by guwirth** [comment] 2016-05-21 08:44
> I think it is the responsibility of the user/developer to correct said error using regular debugging techniques.

Agree

> Static/Global variables are constructed on program startup which will call the Abort constructor. The window will remain open depending on the DiscoveryTimeoutMilliseconds configuration option. Tests from said module will not be listed. I do not think we are in a position to properly identify, handle or log such behavior in the adapter. I think that if the test module causes this kind of error, I think it is the responsibility of the user/developer to correct said error using regular debugging techniques.

Maybe we can document this as hint for the user?

**Comment by netspiri** [comment] 2016-05-23 07:58
Added section to the [Troubleshooting](https://github.com/netspiri/vs-boost-unit-test-adapter/wiki/Troubleshooting) wiki page.

Please review and on confirmation, we will merge with ETAS wiki.

**Comment by netspiri** [comment] 2016-05-30 06:38
ETAS wiki merged with netspiri wiki

**Closed** 2016-05-30 16:00 UTC
Labels: discussion, docu request, invalid
